{"name": "登陆失败-密码错误", "status": "passed", "attachments": [{"name": "stderr", "source": "e14a0345-206e-4c4c-8377-e7bc3e379054-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'id': 3, 'title': '登陆失败-密码错误', 'method': 'post', 'url': 'member/login', 'request_data': '{\"mobile_phone\":\"#general_user#\",\"pwd\":\"12345678\"}', 'expected': None, 'check_sql': None}"}], "start": 1636643787983, "stop": 1636643788271, "uuid": "7528f06f-7171-4a69-888e-f7bec6d17e06", "historyId": "d5ad5b40f9d8d753d5ebb885db2c6171", "testCaseId": "44f56b03f0866dee9fbf282cd6e7f5f6", "fullName": "testcases.test_2_login_api.TestLogin#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('req_assert')"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_2_login_api"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-04EC16A3"}, {"name": "thread", "value": "9236-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_2_login_api"}]}